name: Lint and Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Package
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - name: Lint
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: lint
    - name: Deploy
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}