name: Lint and Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Package
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - name: Lint
      uses: Borales/actions-yarn@v2.3.0
      with:
        cmd: lint